import 'package:flutter/material.dart';

const companyName = "МедОазис";
const accentColor = Color(0xff199A8E);
const secondaryColor = Color(0xffE8F3F1);
const primaryColor = Color(0xffE5E5E5);
const subheadingTextColor = Color(0xff717784);
const headingTextColor = Color(0xff101623);
const bodyTextColor = Color(0xffA1A8B0);
const gradeintColor = Color(0xffF5F7FF);
const inputBG = Color(0xffF9FAFB);
const inputBorder = Color(0xffE5E7EB);
const hintColor = Color(0xffA1A8B0);
const mainTextColor = Color(0xff3B4453);
const alertColor = Color(0xffFF5C5C);
const searchBG = Color(0xffFBFBFB);
const searchIconColor = Color(0xffADADAD);
const cardBorderColor = Color(0xffE8F3F1);
const availabaleTimeColor = Color(0xffB3D3CE);
const notAvailableTimeColor = Color(0xffDEECE9);
const dateColor = Color(0xff555555);
const confirmColor = Color(0xff7BEB78);
