// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqoM1Y7havbBnOibu6wI3xbQefa-OA5Lg',
    appId: '1:237190778825:web:93d2711575ab4d6cd12218',
    messagingSenderId: '237190778825',
    projectId: 'medicalapp-ece20',
    authDomain: 'medicalapp-ece20.firebaseapp.com',
    storageBucket: 'medicalapp-ece20.appspot.com',
    measurementId: 'G-PEZKWD2WFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB82wjKtAOQGxaV2qrV58UwJAf9-t7Nc-g',
    appId: '1:237190778825:android:3aa8a5ac9befcfe0d12218',
    messagingSenderId: '237190778825',
    projectId: 'medicalapp-ece20',
    storageBucket: 'medicalapp-ece20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADT7ynEBzDSUw1-Pi7h3_rNvgcglakObc',
    appId: '1:237190778825:ios:c8e604058cbb4f03d12218',
    messagingSenderId: '237190778825',
    projectId: 'medicalapp-ece20',
    storageBucket: 'medicalapp-ece20.appspot.com',
    iosClientId: '237190778825-c6m5gko9ienjijq25sa49c69g7uunkg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADT7ynEBzDSUw1-Pi7h3_rNvgcglakObc',
    appId: '1:237190778825:ios:f961c3dec86dda1ed12218',
    messagingSenderId: '237190778825',
    projectId: 'medicalapp-ece20',
    storageBucket: 'medicalapp-ece20.appspot.com',
    iosClientId: '237190778825-bemcbfpbjjvodr317vtrqs6pag7s3qio.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalApp.RunnerTests',
  );
}
